apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: itn27qo1p-go
  janus-idp.io/tekton: itn27qo1p-go
  backstage.io/kubernetes-id: itn27qo1p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: itn27qo1p-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
