apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: itn27qo1p-go-gitops
  description: This is GitOps manifest for itn27qo1p-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=itn27qo1p-go
    backstage.io/kubernetes-id: itn27qo1p-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: itn27qo1p-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:itn27qo1p-go
